# permissions for end users to edit blogposts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: blogpost-editor-role
rules:
- apiGroups:
  - javaclub.lviv.ua
  resources:
  - blogposts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - javaclub.lviv.ua
  resources:
  - blogposts/status
  verbs:
  - get
