# permissions for end users to view blogposts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: blogpost-viewer-role
rules:
- apiGroups:
  - javaclub.lviv.ua
  resources:
  - blogposts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - javaclub.lviv.ua
  resources:
  - blogposts/status
  verbs:
  - get
